/*
 * generated by Xtext 2.23.0
 */
package org.metafacture.flux;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FluxRuntimeModule extends AbstractFluxRuntimeModule {
}
