/*
 * generated by Xtext 2.23.0
 */
package org.metafacture.flux.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.metafacture.flux.FluxRuntimeModule;
import org.metafacture.flux.FluxStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FluxIdeSetup extends FluxStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FluxRuntimeModule(), new FluxIdeModule()));
	}
	
}
