/*
 * generated by Xtext 2.23.0
 */

package org.metafacture.flux.ide;

import org.metafacture.flux.FluxRuntimeModule;
import org.metafacture.flux.FluxStandaloneSetup;

import org.eclipse.xtext.util.Modules2;
import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FluxIdeSetup extends FluxStandaloneSetup {

    public FluxIdeSetup() {
    }

    @Override
    public Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new FluxRuntimeModule(), new FluxIdeModule()));
    }

}
