
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Set up vsce
      run: npm install -g vsce
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
        ./gradlew installServer
    - name: Create flux extension
      working-directory: org.metafacture.flux.vsc/
      run: |
        npm install
        vsce package -o flux.vsix
    - name: Pushes vsix to GitHub Pages
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'org.metafacture.flux.vsc/flux.vsix'
        destination_repo: 'metafacture/metafacture.github.io'
        destination_branch: main
        destination_folder: 'ide-extensions'
        user_email: '${{ github.actor }}@users.noreply.github.com'
        user_name: '${{ github.actor }}'
