/**
 * generated by Xtext 2.23.0
 */
package org.metafacture.flux.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.metafacture.flux.flux.Metaflow;
import org.metafacture.flux.tests.FluxInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(FluxInjectorProvider.class)
@SuppressWarnings("all")
public class FluxParsingTest {
  @Inject
  private ParseHelper<Metaflow> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("default base = \"\";");
      _builder.newLine();
      _builder.append("default gndsimple = base + \"gnd-simplified.dat\";");
      _builder.newLine();
      _builder.newLine();
      _builder.append("gnd|");
      _builder.newLine();
      _builder.append("open-file|");
      _builder.newLine();
      _builder.append("as-lines|");
      _builder.newLine();
      _builder.append("decode-pica|");
      _builder.newLine();
      _builder.append("morph(FLUX_DIR + \"format-gnd.xml\")|");
      _builder.newLine();
      _builder.append("encode-formeta(style=\"concise\")|");
      _builder.newLine();
      _builder.append("write(gndsimple);");
      _builder.newLine();
      final Metaflow result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
